FROM node:latest as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf

#docker build -t assiniss/vue-web-app-prod -f Dockerfile-build-app .
#docker run -itd -p 8080:80 assiniss/vue-web-app-prod  